# Generated by Django 3.0.7 on 2020-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liqpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liqpayconfig',
            name='sandbox_mode',
            field=models.BooleanField(default=True, verbose_name='Тестовий режим'),
        ),
    ]
