# Generated by Django 3.0.7 on 2020-09-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_customer', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('sw_catalog', '0004_auto_20200902_1513'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Група з купонами на скидку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sw_customer.CustomerGroup', verbose_name='Група'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='testdrivemodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sw_catalog.Item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='testdriveslider',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sw_catalog.Item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='veloslider',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sw_catalog.Item', verbose_name='Товар'),
        ),
    ]
