# Generated by Django 3.0.7 on 2020-09-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructorform',
            old_name='phone',
            new_name='tel',
        ),
    ]
