# Generated by Django 3.0.7 on 2020-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='similars',
            field=models.ManyToManyField(blank=True, null=True, to='sw_blog.Post', verbose_name='Схожі публікації'),
        ),
    ]
